export const shows = [
  {
    id: 1,
    date: '1/1/21',
    bands: ['The stooges', 'led zeppelin', 'bon jovi'],
    venue: 'TND',
    ageRestriction: true,
    NeedsAnOpener: false,
    flyerImageURL: 'https://via.placeholder.com/150',
    booker: 'brady@dukart.com',
    ticketURL: 'https://google.com',
  },
  {
    id: 2,
    date: '2/2/12',
    bands: ['Baltic to Boardwalk', 'High Hopes', 'No Divinity'],
    venue: 'The Aquarium',
    ageRestriction: false,
    NeedsAnOpener: true,
    flyerImageURL: 'https://via.placeholder.com/150',
    booker: 'brady@dukart.com',
    ticketURL: 'https://google.com',
  },
  {
    id: 3,
    date: '3/3/13',
    bands: ['Steve Miiller Band', 'Creed', 'Iron Maiden'],
    venue: 'The Aquarium',
    ageRestriction: false,
    NeedsAnOpener: true,
    flyerImageURL: 'https://via.placeholder.com/150',
    booker: 'brady@dukart.com',
    ticketURL: 'https://google.com',
  },
];
